### ISSUE TITLE
您好，还是无法运行，缺少模型

### ISSUE THREAD

**Issue by 17702513221** [friedhelm739/Insightface-tensorflow#2]
Traceback (most recent call last):
  File "display.py", line 118, in <module>
    myWin = MyMainWindow()
  File "display.py", line 28, in __init__
    self.recognizer = Arcface_recognizer(config.arc_model_name, config.arc_model_path, config.mtcnn_model_path)
  File "/home/xs/Insightface-tensorflow/recognizer/arcface_recognizer.py", line 51, in __init__
    self.recognizer = recognizer.Recognizer(arc_model_name, arc_model_path, batch_size_to_recognize_one_time, self.img_size_list)
  File "/home/xs/Insightface-tensorflow/recognizer/recognizer.py", line 24, in __init__
    raise Exception("%s is not exists"%(model_name))
Exception: Arcface-330000 is not exists

**Comment by friedhelm739** [comment]
你好，这些模型需要你事先训练的，然后在config文件中更改相应参数，我没有上传训练好的模型

**Comment by friedhelm739** [comment]
@17702513221  你好，这些模型需要你事先训练的，然后在config文件中更改相应模型名称参数，我没有上传训练好的模型
